### ISSUE TITLE
exec /init: exec format error

### ISSUE THREAD

**Issue by otomay** [elryyy/baizoku#2]
### Describe the bug

Hello :) Thanks for you work man, hope it can improve the great idea of kaizoku,

Well, I just set up the docker, and the main container exited with `exec /init: exec format error`
If there's a way to see more logs, please let me know.

### Reproduction steps

1. Edit the docker compose file
2. Deploy
3. See logs from baizoku container

### Additional context

baizoku-redis log:

```
1:C 25 Aug 2023 23:53:54.080 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
1:C 25 Aug 2023 23:53:54.081 * oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 25 Aug 2023 23:53:54.081 * Redis version=7.2.0, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 25 Aug 2023 23:53:54.081 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
1:M 25 Aug 2023 23:53:54.082 * monotonic clock: POSIX clock_gettime
1:M 25 Aug 2023 23:53:54.083 * Running mode=standalone, port=6379.
1:M 25 Aug 2023 23:53:54.083 * Server initialized
1:M 25 Aug 2023 23:53:54.084 * Loading RDB produced by version 7.2.0
1:M 25 Aug 2023 23:53:54.084 * RDB age 85 seconds
1:M 25 Aug 2023 23:53:54.084 * RDB memory usage when created 0.86 Mb
1:M 25 Aug 2023 23:53:54.084 * Done loading RDB, keys loaded: 0, keys expired: 0.
1:M 25 Aug 2023 23:53:54.084 * DB loaded from disk: 0.001 seconds
1:M 25 Aug 2023 23:53:54.084 * Ready to accept connections tcp
```

baizoku-db-1 logs:

```
PostgreSQL Database directory appears to contain a database; Skipping initialization
2023-08-25 23:53:54.168 UTC [1] LOG:  starting PostgreSQL 15.4 on aarch64-unknown-linux-musl, compiled by gcc (Alpine 12.2.1_git20220924-r10) 12.2.1 20220924, 64-bit
2023-08-25 23:53:54.168 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2023-08-25 23:53:54.168 UTC [1] LOG:  listening on IPv6 address "::", port 5432
2023-08-25 23:53:54.174 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2023-08-25 23:53:54.181 UTC [24] LOG:  database system was interrupted; last known up at 2023-08-25 23:52:30 UTC
2023-08-25 23:53:54.193 UTC [24] LOG:  database system was not properly shut down; automatic recovery in progress
2023-08-25 23:53:54.197 UTC [24] LOG:  redo starts at 0/195A588
2023-08-25 23:53:54.198 UTC [24] LOG:  invalid record length at 0/197A8F0: wanted 24, got 0
2023-08-25 23:53:54.198 UTC [24] LOG:  redo done at 0/197A8B8 system usage: CPU: user: 0.00 s, system: 0.00 s, elapsed: 0.00 s
2023-08-25 23:53:54.205 UTC [22] LOG:  checkpoint starting: end-of-recovery immediate wait
2023-08-25 23:53:54.222 UTC [22] LOG:  checkpoint complete: wrote 28 buffers (0.2%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.004 s, sync=0.005 s, total=0.019 s; sync files=7, longest=0.004 s, average=0.001 s; distance=128 kB, estimate=128 kB
2023-08-25 23:53:54.228 UTC [1] LOG:  database system is ready to accept connections
```

docker-compose:

```
version: '3'

volumes:
  db:
  redis:

services:
  app:
    container_name: baizoku
    image: elrylol/baizoku:latest
    environment:
      - DATABASE_URL=postgresql://baizoku:baizoku@db:5432/baizoku
      - BAIZOKU_PORT=3000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PUID=0
      - PGID=0
      - TZ=America/Sao_Paulo
    volumes:
      - /mnt/dockerapps/baizoku/data:/data
      - /mnt/dockerapps/baizoku/config:/config
      - /mnt/dockerapps/baizoku/logs:/logs
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '3000:3000'
  redis:
    image: redis:7-alpine
    volumes:
      - redis:/data
  db:
    image: postgres:alpine
    restart: unless-stopped
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U baizoku']
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=baizoku
      - POSTGRES_DB=baizoku
      - POSTGRES_PASSWORD=baizoku
    volumes:
      - /mnt/dockerapps/baizoku/postgre/db:/var/lib/postgresql/data
```

**Comment by elryyy** [comment]
Oh yeah this repo is not useable atm, im constantly pushing to main and stuff.
The docker image was highly experimental to see how it would work on another pc.
I will look into it if im done with the current thing im working on, cuz currently i cant make a new build.
Check back in 24 for when i push a new Build to docker ^^

**Comment by otomay** [comment]
ehehehe guess I'm to early

sure, thanks :D

**Comment by elryyy** [comment]
Never too early to know of a project, just needs to be ready.

I never did ts, so a few bugs i need to squash first i implemented.

But what and how oae made kaizoku and handles complains about his work attitude is really bad

**Comment by elryyy** [comment]
@otomay Im already done, please do `docker compose up -d --force-recreate` on baizoku and tell me the result :)

**Comment by elryyy** [comment]
Just deployed it to my own media server and it works just fine, i will be closing this.
If you find bugs or have ideas for improvements let me know.

**Comment by otomay** [comment]
hey, sorry about the delay

deleted the old containers and image and did a fresh pull

still seeing the exec format error
nothing new on logs tho

**Comment by otomay** [comment]
just saw the main warning on readme eheheh

**Comment by elryyy** [comment]
What distro / os are you on and how do you install the app ? For me it worked great on my own real machine.

**Comment by otomay** [comment]
it's an ubuntu 22.04 architeture arm 64

**Comment by elryyy** [comment]
Please remove all volumes and containers of kaizoku, baizoku and related redis.

Then in a new folder, create the compose file i have in the read me, adjust the file location and uid and then do `sudo docker compose up`

I have verified with a friend that it works, so something else at your setup seems to be wrong.

But i would wait till the checking of new chapters work anyways (docker version 1.8.0), otherwise it redownloads every episode on a check, cuz the setup of oae doesnt work with my file renaming.

**Comment by otomay** [comment]
Kay, I'm giving another try in a few hours and let you know the results!



> But i would wait till the release of version 1.8.0, otherwise currently it redownloads every episode on a check, cuz the setup of source repo doesnt work with the file renaming.

I don't mind at all. Kaizoku are not working for my porpouse in any level (っ˘̩╭╮˘̩)っ

**Comment by elryyy** [comment]
Yeah Kaizoku gives you wrong chapters, thats completly bad.
